### ISSUE TITLE
ArrayIndexOutOfBoundsException thrown by OgcGeoPackageReader

### ISSUE THREAD

**Issue by emxsys** [NASAWorldWind/WorldWindServerKit#2]
An ArrayIndexOutOfBoundsException is thrown by OgcGeoPackageReader when attempting to render a NSG Profile GeoPackage provided by the AGC.  When this exception occurs the map is not rendered. 

```
org.geoserver.platform.ServiceException: Error rendering coverage on the fast path
        at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:353)
        at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:268)
        at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:138)
        at org.geoserver.wms.GetMap.executeInternal(GetMap.java:623)
        at org.geoserver.wms.GetMap.run(GetMap.java:279)
. . .
Caused by: java.lang.ArrayIndexOutOfBoundsException: 768
        at sun.awt.image.ByteInterleavedRaster.putByteData(ByteInterleavedRaster.java:814)
        at sun.awt.image.ByteInterleavedRaster.setDataElements(ByteInterleavedRaster.java:675)
        at sun.awt.image.ByteInterleavedRaster.setDataElements(ByteInterleavedRaster.java:648)
        at sun.awt.image.ByteInterleavedRaster.setRect(ByteInterleavedRaster.java:1180)
        at gov.nasa.worldwind.geopkg.mosaic.OgcGeoPackageReader.read(OgcGeoPackageReader.java:162)
```

**Comment by emxsys** [comment]
Noted the following errors during initialization of the WWGS in Tomcat after loading the JOG:

- Unable to load kakadu JPEG2000 reader spi
- Unable to load GDAL JP2 ECW Reader SPI
- Unable to load GDAL JP2 MrSID Reader SPI
- Unable to load GDAL JP2 Kakadu Reader SPI

```
12 Jan 06:38:27 INFO [org.geoserver] - Loaded coverage 'AGC_JOG_APG_8_11_v1_3NOV2016'
12 Jan 06:38:27 DEBUG [org.geotools.gce.imagemosaic] - Unable to load kakadu JPEG2000 reader spi
java.lang.ClassNotFoundException: it.geosolutions.imageio.plugins.jp2k.JP2KKakaduImageReaderSpi
...
12 Jan 06:38:30 DEBUG [org.geotools.gce.imagemosaic] - Unable to load GDAL JP2 ECW Reader SPI
java.lang.ClassNotFoundException: it.geosolutions.imageio.plugins.jp2ecw.JP2GDALEcwImageReaderSpi
...
12 Jan 06:38:31 DEBUG [org.geotools.gce.imagemosaic] - Unable to load GDAL JP2 MrSID Reader SPI
java.lang.ClassNotFoundException: it.geosolutions.imageio.plugins.jp2mrsid.JP2GDALMrSidImageReaderSpi
...
12 Jan 06:38:31 DEBUG [org.geotools.gce.imagemosaic] - Unable to load GDAL JP2 Kakadu Reader SPI
java.lang.ClassNotFoundException: it.geosolutions.imageio.plugins.jp2kakadu.JP2GDALKakaduImageReaderSpi
```

**Comment by emxsys** [comment]
Fixed the OgcGeoPackageReader to merge tiles into a mosaic irrespective of the image type of the individual tiles.
